#!/usr/bin/env python3
"""build_contracts.py — config/contracts.json from config/contracts.csv.

The CSV is the exchange's product list with the category hierarchy this site
organises by. It is vendored so a clean checkout builds without it being
fetched from anywhere, and regenerated by running this script.

Nothing here reaches the network. Product ids and names are the exchange's own
public identifiers; the file carries no prices, no strikes and no terms, which
arrive from the exchange at run time.
"""
from __future__ import annotations

import csv
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "config", "contracts.csv")
OUT = os.path.join(ROOT, "config", "contracts.json")

# Where a category is already a page on this site, it keeps that page rather
# than getting a generic listing: the map and the hurricane page are the two
# displays this site was built around.
# ---------------------------------------------------------------- terms
# Which regulatory document governs a product.
#
# Read off each document's own "Product Code:" line rather than off the look of
# the ticker, because the tickers overlap in a way that bites: TRHOU is rain and
# belongs to T[R/S][region], while TR[Jurisdiction] is TAX REVENUE with its own
# document. Matching on the longest prefix would put tax-revenue terms on five
# weather pages. The rules below are ordered, most specific first, and every
# product is checked against them by scripts/build_contracts.py.
TERMS_BASE = "https://data.forecastex.com/regulatory/"
TERMS_RULES = [
    (r"^(GT|GTM|GTTA|GTTM|MRT|RT|UST|USTM|ACD|MACD|GSL|AMOCW|GCE|USCE|USDR|NGP|OP|USGP|CFSFP|HELPP|HLF|HLFRE)$", None),
    (r"^GCY[A-Z]{2}$", "GCY"),
    (r"^ELGP[A-Z]$", "ELGP"),
    (r"^HCAT\d$", "HCAT"),
    (r"^MHC[MY]?[A-Z]$", "MHC"),
    (r"^TROP[A-Z]$", "TROP"),
    (r"^HC[A-Z]{2}$", "HC"),
    (r"^FUS[A-Z]{2}$", "FUS"),
    (r"^SW[A-Z][A-Z]{2}$", "SW"),
    (r"^H[WS][HC][A-Z]{2}$", "H"),
    (r"^T[RS][A-Z]{3}$", "T"),
    (r"^W[A-Z]{2,4}$", "W"),
    (r"^AE[A-Z]{2}[A-Z]$", "AE"),
    (r"^RE[A-Z]{2}[A-Z]$", "RE"),
    (r"^[CE][MY][A-Z]{2}[A-Z]$", None),
    (r"^GS[A-Z]{3}$", "GS"),
    (r"^AW[A-Z]{3}$", "AW"),
    (r"^MG[A-Z]{3}$", "MG"),
    (r"^HO[A-Z]{3}$", "HO"),
    (r"^TA[A-Z]{3}$", "TA"),
    (r"^A\d[A-Z]{3}$", "A"),
    (r"^O[AHL][A-Z]{3}$", "O"),
    # the daily temperature document names U and S codes; the D series carries
    # the same product ("Atlanta Daily Temperature High") and the same question,
    # so it is governed by that document even though the pattern predates it
    (r"^[USD][HLA][A-Z]{3}$", "DailyTemperature"),
]


def terms_url(pid):
    """The document that governs this product, or None when none is published."""
    import re as _re
    for pat, name in TERMS_RULES:
        if _re.match(pat, pid):
            if name is None:
                name = pid[0] if (pid[0] in "CE" and len(pid) == 5) else pid
            return TERMS_BASE + name + "TermsandConditions.pdf"
    return None


CATEGORY_PAGE = {
    "daily-temperatures": "index.html",
    "tropical-cyclones": "hurricane.html",
    "climate-change": "climate.html",
    "agriculture": "agriculture.html",
    "weather": "weather.html",
    "fossil-fuels": "fossil-fuels.html",
    "electricity-renewables": "electricity-renewables.html",
}
ORDER_L1 = ["Climate & Weather", "Energy"]
ORDER_L2 = {
    "Climate & Weather": ["Daily Temperatures", "Tropical Cyclones", "Climate Change", "Weather", "Agriculture"],
    "Energy": ["Fossil Fuels", "Electricity & Renewables"],
}


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")


def main() -> int:
    rows = list(csv.DictReader(open(SRC, encoding="utf-8-sig")))
    products, seen = [], set()
    for r in rows:
        pid = (r.get("product_id") or "").strip().upper()
        if not pid or pid in seen:
            continue
        seen.add(pid)
        products.append({
            "id": pid,
            "name": (r.get("name") or "").strip(),
            "active": (r.get("is_active") or "").strip().upper() == "TRUE",
            "l1": (r.get("new_l1") or "").strip(),
            "l2": (r.get("new_l2") or "").strip(),
            # the exchange's own grouping, kept so a contract can be found on
            # its site as well as this one
            "was": " / ".join(x for x in ((r.get("category_l2") or "").strip(),
                                          (r.get("category_l3") or "").strip()) if x),
            "terms": terms_url(pid),
        })
    products.sort(key=lambda p: (ORDER_L1.index(p["l1"]) if p["l1"] in ORDER_L1 else 9,
                                 ORDER_L2.get(p["l1"], []).index(p["l2"]) if p["l2"] in ORDER_L2.get(p["l1"], []) else 9,
                                 not p["active"], p["id"]))

    cats = []
    for l1 in ORDER_L1:
        for l2 in ORDER_L2[l1]:
            here = [p for p in products if p["l1"] == l1 and p["l2"] == l2]
            if not here:
                continue
            s = slug(l2)
            cats.append({"l1": l1, "l1slug": slug(l1), "l2": l2, "slug": s,
                         "page": CATEGORY_PAGE.get(s, "category.html?c=" + s),
                         "n": len(here), "active": sum(1 for p in here if p["active"])})
    doc = {"schema": 1, "l1": [{"name": n, "slug": slug(n)} for n in ORDER_L1],
           "categories": cats, "products": products}
    with open(OUT, "w") as f:
        json.dump(doc, f, separators=(",", ":"))
        f.write("\n")
    print(json.dumps({"products": len(products), "active": sum(1 for p in products if p["active"]),
                      "categories": len(cats)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
