"""
build.py — the two build targets from one codebase.

    python3 scripts/build.py                  # both targets, local mode (sample snapshots bundled)
    python3 scripts/build.py --live           # bundle data/snapshots instead of samples
    python3 scripts/build.py --deploy         # no data bundled; pages read DATA_BASE_URL from config

Output: dist/standalone/ (the full site) and dist/embed/ (the single chart).
Each gets a generated config.js that carries the site configuration the
pages read (data base URL, target, market switch, disclosure, cadences).
Nothing in site/ is vendor-specific; the deploy step copies dist/ to the host.
"""
from __future__ import annotations
import argparse
import json
import os
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from pipeline import config    # noqa: E402

SITE = os.path.join(ROOT, "site")
DIST = os.path.join(ROOT, "dist")

SHARED = ["css/site.css", "js/theme.js", "js/common.js", "js/data.js", "js/market.js"]
STANDALONE = ["index.html", "city.html", "hurricane.html", "about.html", "scorecard.html", "climate.html",
              "faq.html", "accuracy.html", "daily-temperature-markets.html",
              "section.html", "category.html", "contract.html", "js/catalogue.js",
              "js/chart-city.js", "js/city-score.js", "js/map.js", "js/hurricane.js", "js/storm.js", "js/scorecard.js", "js/climate.js",
              "assets/basemap.json", "assets/world.json", "assets/hurricane-geo.json"]
EMBED = ["embed/index.html", "js/chart-city.js"]


def config_js(cfg: dict, target: str, data_base: str) -> str:
    market = (cfg.get("market_overlay") or {}).get(target, "off")
    wx = {
        "target": target,
        "siteTitle": cfg.get("site_title") or cfg.get("site_name") or "Weather tools",
        "domain": cfg.get("domain", ""),
        "dataBaseUrl": data_base,
        "market": market,
        "marketSource": (cfg.get("market_overlay") or {}).get("source", "placeholder"),
        "feePerSide": (cfg.get("exchange") or {}).get("fee_per_side", 0.005),
        "disclosure": cfg.get("disclosure", ""),
        "cadenceMinutes": cfg.get("cadence_minutes", {}),
        "decode": {"TEMP_SOURCE": None, "INCLUDE_SPECI": None},
    }
    # the category hierarchy travels in config.js so the header can be drawn on
    # the first paint rather than after a fetch: it is small, it changes only
    # when the registry is rebuilt, and every page needs it
    reg = cfg.get("contracts") or {}
    if reg.get("categories"):
        slug_of = {c["l2"]: c["slug"] for c in reg["categories"]}
        wx["nav"] = {"l1": reg.get("l1") or [],
                     "categories": [{k: c[k] for k in ("l1", "l1slug", "l2", "slug", "page", "n", "active")}
                                    for c in reg["categories"]],
                     # product -> category slug, so a contract page knows which
                     # branch it belongs to before any data has been fetched
                     "product": {p["id"]: slug_of.get(p["l2"], "") for p in (reg.get("products") or [])}}
    return "/* generated by scripts/build.py; edit config/site.json instead */\nwindow.WX = " + json.dumps(wx, indent=1) + ";\n"


def copy(rel: str, dst_root: str, flatten_embed: bool = False) -> bool:
    src = os.path.join(SITE, rel)
    if not os.path.exists(src):
        return False
    out_rel = "index.html" if (flatten_embed and rel == "embed/index.html") else rel
    dst = os.path.join(dst_root, out_rel)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy2(src, dst)
    return True


def build(target: str, cfg: dict, data_mode: str) -> dict:
    out = os.path.join(DIST, target)
    if os.path.isdir(out):
        shutil.rmtree(out)
    os.makedirs(out)
    files = SHARED + (STANDALONE if target == "standalone" else EMBED)
    missing = [f for f in files if not copy(f, out, flatten_embed=True)]
    data_base = cfg.get("data_base_url", "/data") if data_mode == "deploy" else "data"
    with open(os.path.join(out, "config.js"), "w") as fh:
        fh.write(config_js(cfg, target, data_base))
    bundled = 0
    if data_mode != "deploy":
        src = os.path.join(ROOT, "data" if data_mode == "live" else "samples", "snapshots")
        if os.path.isdir(src):
            shutil.copytree(src, os.path.join(out, "data", "snapshots"))
            bundled = sum(len(f) for _, _, f in os.walk(src))
    return {"target": target, "files": len(files) - len(missing), "missing": missing, "snapshots": bundled,
            "dataBaseUrl": data_base}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--live", action="store_true", help="bundle data/snapshots instead of samples/")
    ap.add_argument("--deploy", action="store_true", help="bundle no data; pages read data_base_url from config")
    ap.add_argument("--target", choices=["standalone", "embed"], help="build one target only")
    args = ap.parse_args(argv)
    cfg = config.load()
    mode = "deploy" if args.deploy else ("live" if args.live else "samples")
    for target in ([args.target] if args.target else ["standalone", "embed"]):
        r = build(target, cfg, mode)
        print(f"{target}: {r['files']} files, {r['snapshots']} snapshots bundled, data at {r['dataBaseUrl']!r}"
              + (f", missing {r['missing']}" if r["missing"] else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
