#!/usr/bin/env python3
"""build_contracts.py — config/contracts.json from config/contracts.csv.

The CSV is the exchange's product list with the category hierarchy this site
organises by. It is vendored so a clean checkout builds without it being
fetched from anywhere, and regenerated by running this script.

Nothing here reaches the network. Product ids and names are the exchange's own
public identifiers; the file carries no prices, no strikes and no terms, which
arrive from the exchange at run time.
"""
from __future__ import annotations

import csv
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "config", "contracts.csv")
OUT = os.path.join(ROOT, "config", "contracts.json")

# Where a category is already a page on this site, it keeps that page rather
# than getting a generic listing: the map and the hurricane page are the two
# displays this site was built around.
CATEGORY_PAGE = {
    "daily-temperatures": "index.html",
    "tropical-cyclones": "hurricane.html",
    "climate-change": "climate.html",
}
ORDER_L1 = ["Climate & Weather", "Energy"]
ORDER_L2 = {
    "Climate & Weather": ["Daily Temperatures", "Tropical Cyclones", "Climate Change", "Weather", "Agriculture"],
    "Energy": ["Fossil Fuels", "Electricity & Renewables"],
}


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")


def main() -> int:
    rows = list(csv.DictReader(open(SRC, encoding="utf-8-sig")))
    products, seen = [], set()
    for r in rows:
        pid = (r.get("product_id") or "").strip().upper()
        if not pid or pid in seen:
            continue
        seen.add(pid)
        products.append({
            "id": pid,
            "name": (r.get("name") or "").strip(),
            "active": (r.get("is_active") or "").strip().upper() == "TRUE",
            "l1": (r.get("new_l1") or "").strip(),
            "l2": (r.get("new_l2") or "").strip(),
            # the exchange's own grouping, kept so a contract can be found on
            # its site as well as this one
            "was": " / ".join(x for x in ((r.get("category_l2") or "").strip(),
                                          (r.get("category_l3") or "").strip()) if x),
        })
    products.sort(key=lambda p: (ORDER_L1.index(p["l1"]) if p["l1"] in ORDER_L1 else 9,
                                 ORDER_L2.get(p["l1"], []).index(p["l2"]) if p["l2"] in ORDER_L2.get(p["l1"], []) else 9,
                                 not p["active"], p["id"]))

    cats = []
    for l1 in ORDER_L1:
        for l2 in ORDER_L2[l1]:
            here = [p for p in products if p["l1"] == l1 and p["l2"] == l2]
            if not here:
                continue
            s = slug(l2)
            cats.append({"l1": l1, "l1slug": slug(l1), "l2": l2, "slug": s,
                         "page": CATEGORY_PAGE.get(s, "category.html?c=" + s),
                         "n": len(here), "active": sum(1 for p in here if p["active"])})
    doc = {"schema": 1, "l1": [{"name": n, "slug": slug(n)} for n in ORDER_L1],
           "categories": cats, "products": products}
    with open(OUT, "w") as f:
        json.dump(doc, f, separators=(",", ":"))
        f.write("\n")
    print(json.dumps({"products": len(products), "active": sum(1 for p in products if p["active"]),
                      "categories": len(cats)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
